from __future__ import annotations

import io
from typing import Literal

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response, StreamingResponse
from pydantic import BaseModel

from docx import Document
from docx.shared import Pt

from services import search_service, gemini_service, db_service

router = APIRouter()


class ExportRequest(BaseModel):
    case_id: str
    year: int
    format: Literal["md", "docx"]


def _render_markdown(meta: dict, b: dict) -> str:
    def _bullets(items: list[str]) -> str:
        if not items:
            return "_None recorded._\n"
        return "\n".join(f"- {i}" for i in items) + "\n"

    parts = [
        f"# {meta.get('title', 'Judgment')}",
        "",
        f"**Citation:** {meta.get('citation', '')}  ",
        f"**INSC:** {meta.get('case_id', '')}  ",
        f"**Court:** {meta.get('court', '')}  ",
        f"**Date:** {meta.get('date', '')}  ",
        f"**Judges:** {meta.get('judges', '')}  ",
        f"**Outcome:** {meta.get('outcome', '')}",
        "",
        "## Facts",
        b.get("facts", "") or "_Not available._",
        "",
        "## Issues",
        _bullets(b.get("issues", [])),
        "## Arguments — Petitioner",
        _bullets(b.get("arguments_petitioner", [])),
        "## Arguments — Respondent",
        _bullets(b.get("arguments_respondent", [])),
        "## Judgment",
        b.get("judgment", "") or "_Not available._",
        "",
        "## Ratio Decidendi",
        b.get("ratio_decidendi", "") or "_Not available._",
        "",
        "## Conclusion",
        b.get("conclusion", "") or "_Not available._",
        "",
        "## Acts Cited",
        _bullets(b.get("acts_cited", [])),
        "## Cases Cited",
        _bullets(b.get("cases_cited", [])),
        "---",
        "_Generated by LegalAI — AI-assisted analysis. Not legal advice._",
    ]
    return "\n".join(parts)


def _render_docx(meta: dict, b: dict) -> bytes:
    doc = Document()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    doc.add_heading(meta.get("title", "Judgment"), level=0)

    meta_pairs = [
        ("Citation", meta.get("citation", "")),
        ("INSC", meta.get("case_id", "")),
        ("Court", meta.get("court", "")),
        ("Date", meta.get("date", "")),
        ("Judges", meta.get("judges", "")),
        ("Outcome", meta.get("outcome", "")),
    ]
    for label, val in meta_pairs:
        p = doc.add_paragraph()
        run = p.add_run(f"{label}: ")
        run.bold = True
        p.add_run(str(val))

    def _section(title: str, body: str) -> None:
        doc.add_heading(title, level=1)
        doc.add_paragraph(body or "Not available.")

    def _bullets(title: str, items: list[str]) -> None:
        doc.add_heading(title, level=1)
        if not items:
            doc.add_paragraph("None recorded.")
            return
        for item in items:
            doc.add_paragraph(item, style="List Bullet")

    _section("Facts", b.get("facts", ""))
    _bullets("Issues", b.get("issues", []))
    _bullets("Arguments — Petitioner", b.get("arguments_petitioner", []))
    _bullets("Arguments — Respondent", b.get("arguments_respondent", []))
    _section("Judgment", b.get("judgment", ""))
    _section("Ratio Decidendi", b.get("ratio_decidendi", ""))
    _section("Conclusion", b.get("conclusion", ""))
    _bullets("Acts Cited", b.get("acts_cited", []))
    _bullets("Cases Cited", b.get("cases_cited", []))

    doc.add_paragraph()
    footer = doc.add_paragraph()
    fr = footer.add_run("Generated by LegalAI — AI-assisted analysis. Not legal advice.")
    fr.italic = True
    fr.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


@router.post("/api/export")
async def export_breakdown(req: ExportRequest):
    case_data = search_service.load_case_json(req.case_id, req.year)
    if not case_data:
        raise HTTPException(status_code=404, detail="Case not found")

    # Cache lookup
    breakdown = await db_service.get_cached_breakdown(req.case_id)
    if not breakdown:
        full_text = search_service.get_full_text(case_data, max_chars=14_000)
        breakdown = await gemini_service.get_breakdown(full_text)
        is_error = (breakdown.get("facts", "").startswith("Error generating") or
                    not breakdown.get("facts"))
        if not is_error:
            try:
                await db_service.set_cached_breakdown(req.case_id, req.year, breakdown)
            except Exception as e:
                print(f"[export] cache write failed: {e}")

    meta = {
        "case_id":   case_data.get("case_id", ""),
        "citation":  case_data.get("citation", ""),
        "title":     case_data.get("title", ""),
        "judges":    case_data.get("judges", ""),
        "date":      case_data.get("date", ""),
        "year":      case_data.get("year", req.year),
        "outcome":   case_data.get("outcome", ""),
        "court":     case_data.get("court", "Supreme Court of India"),
    }

    safe_name = (meta["case_id"] or "judgment").replace(" ", "_").replace("/", "-")

    if req.format == "md":
        md = _render_markdown(meta, breakdown)
        return Response(
            content=md,
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="{safe_name}.md"'},
        )

    # docx
    docx_bytes = _render_docx(meta, breakdown)
    return StreamingResponse(
        io.BytesIO(docx_bytes),
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}.docx"'},
    )
